name: linux

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  schedule:
  - cron: "0 5 * * 1"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      fail-fast: false

    steps:
    - uses: actions/checkout@v1
    - name: Install conda
      run: bash .github/workflows/scripts/conda_install_linux.sh
    - name: Include Conda in PATH
      run: echo ::add-path::$HOME/miniconda/bin
    - name: Setup conda and env
      run: bash .github/workflows/scripts/conda_setup.sh
    - name: pre-commit Checkers and Formatters
      run: |
        source activate autostep
        pre-commit install
        pre-commit run --all-files
    - name: Test with pytest
      run: |
        source activate autostep
        pytest . -n auto --cov-config=.coveragerc --cov-report=xml --cov=autostep
        pytest $AUTOSTEP_NOTEBOOKS_DIR --nbval
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.0.3
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./coverage.xml
