name: linux

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  schedule:
  - cron: "0 5 * * 1"

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: de59c83c-8155-401a-a5c5-56dd3ccc7e15
    strategy:
      max-parallel: 4
      fail-fast: false

    steps:
    - uses: actions/checkout@v1
    - name: Install conda
      run: bash .github/workflows/scripts/conda_install_linux.sh
    - name: Include $CONDA in $PATH
      run: echo ::add-path::$CONDA/bin
    - name: Setup conda and env
      run: |
        conda config --set always_yes yes --set changeps1 no
        conda config --add channels conda-forge
        conda install conda-devenv
        conda update -q conda
        conda info -a
        conda devenv
        conda activate autostep
    - name: pre-commit Checkers and Formatters
      run: |
        pre-commit install
        pre-commit run --all-files
    - name: Test with pytest
      run: |
        pytest . --cov-config=.coveragerc --cov-report=xml --cov=autostep
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.0.3
      with:
        token: ${{env.CODECOV_TOKEN}}
        file: ./coverage.xml
