name: osx

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  schedule:
  - cron: "0 5 * * 1"

jobs:
  build:

    runs-on: macOS-latest
    strategy:
      max-parallel: 4
      fail-fast: false

    steps:
    - uses: actions/checkout@v1
    - name: Install conda
      run: bash .github/workflows/scripts/conda_install_osx.sh
    - name: Setup conda and env
      run: bash .github/workflows/scripts/conda_setup.sh
    - name: pre-commit Checkers and Formatters
      run: |
        pre-commit install
        pre-commit run --all-files
    - name: Test with pytest
      run: |
        pytest .
