name: windows

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  schedule:
  - cron: "0 5 * * 1"

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 20
    strategy:
      max-parallel: 4
      fail-fast: false

    steps:
    - uses: actions/checkout@v1
    - name: Setup conda
      shell: cmd
      run: |
        set PATH=%CONDA%;%CONDA%\Scripts;%CONDA%\Library\bin;%PATH%
        conda config --set always_yes yes --set changeps1 no
        conda config --add channels conda-forge
        conda install conda-devenv
        conda update -q conda
        conda info -a
        conda devenv
    - name: pre-commit Checkers and Formatters
      shell: cmd
      run: |
        set PATH=%CONDA%;%CONDA%\Scripts;%CONDA%\Library\bin;%PATH%
        call activate autostep
        pre-commit install
        pre-commit run --all-files
    - name: Test with pytest
      shell: cmd
      run: |
        set PATH=%CONDA%;%CONDA%\Scripts;%CONDA%\Library\bin;%PATH%
        call activate autostep
        pytest . -n auto
